### ISSUE TITLE
refactor polkadot.js instantiation api undefined

### ISSUE THREAD

**Issue by VadneyK** [PlasmNetwork/dusty-faucet#10]
Trying to instantiate the polkadot.js api at the same time as the discord api since it's a global constant that could be used my other functions. However I am getting this odd error at this commit:

console.log() here:
https://github.com/PlasmNetwork/dusty-faucet/blob/3c7b3f372f5863676188c3595a12ed43039f3be3/app/src/app.ts#L98

passed into this function and the api just becomes undefined:
https://github.com/PlasmNetwork/dusty-faucet/blob/3c7b3f372f5863676188c3595a12ed43039f3be3/app/src/helpers/sendTokens.ts#L13

I tried setting api: any but it's still not working:

![Screen Shot 2021-06-15 at 1 13 22 PM](https://user-images.githubusercontent.com/57117207/122117237-776b8880-cddb-11eb-869e-b011df3fba8d.png)

Starting bot server...
Plasm Faucet has started
Promise {
  ApiPromise {
    __phantom: BN { negative: 0, words: [Array], length: 1, red: null },
    _consts: {
      system: [Object],
      timestamp: [Object],
      transactionPayment: [Object],
      indices: [Object],
      balances: [Object],
      contracts: [Object],
      plasmRewards: [Object],
      babe: [Object],
      nicks: [Object]
    },
    _derive: {
      accounts: [Object],
      balances: [Object],
      bounties: [Object],
      chain: [Object],
      contracts: [Object],
      imOnline: [Object],
      session: [Object],
      tx: [Object]
    },
    _errors: {
      system: [Object],
      authorship: [Object],
      scheduler: [Object],
      balances: [Object],
      contracts: [Object],
      plasmRewards: [Object],
      session: [Object],
      grandpa: [Object],
      imOnline: [Object],
      operator: [Object],
      sudo: [Object],
      nicks: [Object],
      evm: [Object],
      ethCall: [Object]
    },
    _events: {
      system: [Object],
      utility: [Object],
      scheduler: [Object],
      indices: [Object],
      balances: [Object],
      contracts: [Object],
      plasmValidator: [Object],
      plasmRewards: [Object],
      session: [Object],
      grandpa: [Object],
      imOnline: [Object],
      offences: [Object],
      operator: [Object],
      sudo: [Object],
      nicks: [Object],
      ethereum: [Object],
      evm: [Object],
      ethCall: [Object]
    },
    _extrinsics: [Function (anonymous)] {
      system: [Object],
      utility: [Object],
      timestamp: [Object],
      authorship: [Object],
      scheduler: [Object],
      indices: [Object],
      balances: [Object],
      contracts: [Object],
      plasmValidator: [Object],
      plasmRewards: [Object],
      session: [Object],
      babe: [Object],
      grandpa: [Object],
      imOnline: [Object],
      offences: {},
      operator: [Object],
      randomnessCollectiveFlip: {},
      sudo: [Object],
      nicks: [Object],
      ethereum: [Object],
      evm: [Object],
      ethCall: [Object]
    },
    _extrinsicType: 4,
    _genesisHash: Type(32) [Uint8Array] [
      186,
      221,
      26,
      252,
      171,
      100,
      114,
      70,
      249,
      108,
      7,
      39,
      153,
      245,
      25,
      244,
      81,
      207,
      145,
      105,
      12,
      2,
      5,
      24,
      86,
      166,
      177,
      217,
      177,
      148,
      163,
      96,
      registry: [TypeRegistry],
      createdAtHash: undefined
    ],
    _isConnected: BehaviorSubject {
      _isScalar: false,
      observers: [],
      closed: false,
      isStopped: false,
      hasError: false,
      thrownError: null,
      _value: true
    },
    _isReady: true,
    _options: { provider: WsProvider {}, types: [Object] },
    _query: {
      substrate: [Object],
      system: [Object],
      timestamp: [Object],
      authorship: [Object],
      transactionPayment: [Object],
      scheduler: [Object],
      indices: [Object],
      balances: [Object],
      contracts: [Object],
      plasmValidator: [Object],
      plasmRewards: [Object],
      session: [Object],
      babe: [Object],
      grandpa: [Object],
      imOnline: [Object],
      offences: [Object],
      operator: [Object],
      randomnessCollectiveFlip: [Object],
      sudo: [Object],
      nicks: [Object],
      ethereum: [Object],
      evm: [Object]
    },
    _queryMulti: [Function (anonymous)],
    _rpc: {
      babe: [Object],
      beefy: {},
      contracts: [Object],
      engine: {},
      grandpa: [Object],
      mmr: {},
      syncstate: {},
      system: [Object],
      eth: [Object],
      net: [Object],
      web3: [Object],
      rpc: [Object],
      author: [Object],
      chain: [Object],
      childstate: [Object],
      offchain: [Object],
      payment: [Object],
      state: [Object]
    },
    _rpcCore: RpcCore {
      mapping: [Map],
      provider: WsProvider {},
      sections: [Array],
      babe: [Object],
      beefy: [Object],
      contracts: [Object],
      engine: [Object],
      grandpa: [Object],
      mmr: [Object],
      syncstate: [Object],
      system: [Object],
      eth: [Object],
      net: [Object],
      web3: [Object],
      rpc: [Object],
      author: [Object],
      chain: [Object],
      childstate: [Object],
      offchain: [Object],
      payment: [Object],
      state: [Object]
    },
    _runtimeChain: [String (Text): 'Dusty'] {
      registry: [TypeRegistry],
      createdAtHash: undefined
    },
    _runtimeMetadata: Metadata(2) [Map] {
      'magicNumber' => [MagicNumber],
      'metadata' => [Type],
      registry: [TypeRegistry],
      createdAtHash: undefined
    },
    _runtimeVersion: Type(7) [Map] {
      'specName' => [Text],
      'implName' => [Text],
      'authoringVersion' => [u32],
      'specVersion' => [u32],
      'implVersion' => [u32],
      'apis' => [Vec],
      'transactionVersion' => [u32],
      registry: [TypeRegistry],
      createdAtHash: undefined,
      specName: [Getter],
      implName: [Getter],
      authoringVersion: [Getter],
      specVersion: [Getter],
      implVersion: [Getter],
      apis: [Getter],
      transactionVersion: [Getter]
    },
    _rx: {
      consts: [Object],
      query: [Object],
      tx: [Function],
      registry: [TypeRegistry],
      hasSubscriptions: true,
      rpc: [Object],
      queryMulti: [Function (anonymous)],
      signer: undefined,
      runtimeVersion: [Type [Map]],
      extrinsicType: 4,
      genesisHash: [Type [Uint8Array]],
      derive: [Object]
    },
    _type: 'promise',
    _decorateMethod: [Function: decorateMethod],
    _rxDecorateMethod: [Function (anonymous)]
  }
}
TypeRegistry { createdAtHash: undefined }
above are the api info before being passed in a function
/Users/kentarovadney/Desktop/code/dusty-faucet/app/build/helpers/sendTokens.js:24
    yield api.isReady;
              ^

TypeError: Cannot read property 'isReady' of undefined
    at /Users/kentarovadney/Desktop/code/dusty-faucet/app/build/helpers/sendTokens.js:24:15
    at Generator.next (<anonymous>)
    at /Users/kentarovadney/Desktop/code/dusty-faucet/app/build/helpers/sendTokens.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/kentarovadney/Desktop/code/dusty-faucet/app/build/helpers/sendTokens.js:4:12)
    at Object.sendTokens (/Users/kentarovadney/Desktop/code/dusty-faucet/app/build/helpers/sendTokens.js:23:44)
    at drip.execute (/Users/kentarovadney/Desktop/code/dusty-faucet/app/build/commands/drip.js:16:25)
    at Client.<anonymous> (/Users/kentarovadney/Desktop/code/dusty-faucet/app/build/app.js:86:25)
    at Client.emit (node:events:365:28)
    at MessageCreateAction.handle (/Users/kentarovadney/Desktop/code/dusty-faucet/app/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
kentarovadney@Kentaros-MacBook-Air app %

**Comment by jacogr** [comment]
That is an issue in your code, not the API itself. The object references are not mishandled in the API.

**Comment by VadneyK** [comment]
https://github.com/polkadot-js/api/issues/3660

**Comment by VadneyK** [comment]
Totally forgot that the api is passed to `drip.ts` then `sendToken.ts` so I just had to change the signature of the function in `drip.ts` and pass it in on the call to sendToken.ts
![Screen Shot 2021-06-16 at 9 34 14 PM](https://user-images.githubusercontent.com/57117207/122332012-999ffc00-ceea-11eb-8620-a5e4ba009ab0.png)
