### ISSUE TITLE
commands modules not exporting

### ISSUE THREAD

**Issue by VadneyK** [PlasmNetwork/dusty-faucet#3]
[This code ](https://github.com/PlasmNetwork/dusty-faucet/tree/main/app/src)works in regular js but isn't working in ts. I think it may have something to do with how exports work differently or how the ts is compiled to a js file before executed, but I can't pin down what exactly the issue is.

If I can't figure this out I will have to refactor the drip.ts to be a class and export that class instead of auto-loading all of the file and filenames via the nodejs file fetching function `fs.readdirSync('src/commands');`

![Screen Shot 2021-06-07 at 9 26 54 PM](https://user-images.githubusercontent.com/57117207/121122881-15a59000-c7d7-11eb-9502-62d935b0a999.png)

**Comment by VadneyK** [comment]
Alternatively I could just leave the commands folder as a .js file and reference the folder in outside of the build with the compiled folder since the .js files will not be compiles with yarn start, but this sounds like bad practice...

**Comment by hskang9** [comment]
I think running node ./build/index.js in current working directory `dusty-faucet/app` causes ecmascript to find ts files in current working directory. So running the same command `yarn run build && NODE_ENV=production node -r dotenv/config ./index.js` in cwd of `dusty-faucet/app/build` will solve the problem.

**Comment by VadneyK** [comment]
I can't seem to load the .env file environment variables for some reason... @hskang9 
kentarovadney@Kentaros-MacBook-Air build % yarn run build && NODE_ENV=production node -r dotenv/config ./index.js
yarn run v1.22.10
warning ../../../../package.json: No license field
$ tsc --project tsconfig.json
✨  Done in 5.94s.
Starting bot server...
Error: Please provide discord bot credentials
    at Object.main [as default] (/Users/kentarovadney/Desktop/code/dusty-faucet/app/build/app.js:9:15)
    at /Users/kentarovadney/Desktop/code/dusty-faucet/app/build/index.js:9:18
    at Object.<anonymous> (/Users/kentarovadney/Desktop/code/dusty-faucet/app/build/index.js:12:3)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
kentarovadney@Kentaros-MacBook-Air build %

**Comment by VadneyK** [comment]
moved .env to the build directory but now am having this issue, seems like an interpreter issue?

![Screen Shot 2021-06-08 at 8 12 27 PM](https://user-images.githubusercontent.com/57117207/121287128-db4ef800-c895-11eb-9251-f651616fbe05.png)

**Comment by VadneyK** [comment]
don't require cargo-contract https://github.com/paritytech/ink/issues/805

**Comment by VadneyK** [comment]
It seems like the carrot is pointing to the ':' in "version":3 but this doesn't make much sense. It seems like nodejs engine is having trouble reading the .map file, so I deleted the drip.js.map file so that the nodejs engine just goes to the non-optimized .js file instead of .js.map. We should still ideally fix this error for when we push to prod so we can use optimized .js.map

**Comment by VadneyK** [comment]
need to filter out .map files in going through all folders. https://github.com/microsoft/TypeScript/issues/5649

**Comment by VadneyK** [comment]
It seems that since the .ts is converted to comminJs in .js, the class no longer keeps its 'name' attribute so it's undefined in the build/drip.js. I can change that directly in the compiled file but how do I ensure the classes don't lose properties when converting from .ts to .js?

![Screen Shot 2021-06-09 at 9 15 25 AM](https://user-images.githubusercontent.com/57117207/121391445-3cf97b80-c903-11eb-86fa-e4261a8b54fc.png)

**Comment by VadneyK** [comment]
https://github.com/discordjs/discord.js/issues/5790#issuecomment-858098195
