### ISSUE TITLE
need to use a V3 contracts module?

### ISSUE THREAD

**Issue by VadneyK** [PlasmNetwork/dusty-faucet#8]
not sure what this means

![Screen Shot 2021-06-12 at 3 27 13 PM](https://user-images.githubusercontent.com/57117207/121790329-2701ea00-cb93-11eb-9933-10e06296c199.png)

**Comment by NukeManDan** [comment]
The API expects v3.0.0 or higher I would presume: https://github.com/paritytech/substrate/blob/master/frame/contracts/Cargo.toml#L3

**Comment by VadneyK** [comment]
the plasm node does implement thv3.0.0 pallet-contracts: https://github.com/PlasmNetwork/Plasm/search?q=pallet-contracts
for the smart contract I deployed, everything is 3.0.0: https://github.com/PlasmNetwork/dusty-faucet/blob/main/contract/Cargo.toml do I have to get rid of the `^` ?

**Comment by VadneyK** [comment]
tried on the local node at `wss://127.0.0.1:9944` but am still getting the same issue. Is this an issue with the smart contract I am interacting with? I just deployed the contract [here](https://github.com/PlasmNetwork/dusty-faucet/tree/main/contract)

kentarovadney@Kentaros-MacBook-Air app % yarn
yarn install v1.22.10
warning ../../../../package.json: No license field
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.20s.
kentarovadney@Kentaros-MacBook-Air app % yarn start
yarn run v1.22.10
warning ../../../../package.json: No license field
$ yarn run serve
warning ../../../../package.json: No license field
$ cd build && yarn run build && NODE_ENV=production node -r dotenv/config ./index.js
warning ../../../../package.json: No license field
$ tsc --project tsconfig.json
Starting bot server...
Plasm Faucet has started
/Users/kentarovadney/Desktop/code/dusty-faucet/app/node_modules/@polkadot/util/assert.cjs:34
    throw new Error((0, _function.isFunction)(message) ? message() : message);
          ^

Error: You need to connect to a node with a V3 contracts module. Your node does not expose api.tx.contracts.instantiateWithCode on this instance
    at assert (/Users/kentarovadney/Desktop/code/dusty-faucet/app/node_modules/@polkadot/util/assert.cjs:34:11)
    at new Base (/Users/kentarovadney/Desktop/code/dusty-faucet/app/node_modules/@polkadot/api-contract/base/Base.cjs:26:22)
    at new Contract (/Users/kentarovadney/Desktop/code/dusty-faucet/app/node_modules/@polkadot/api-contract/base/Contract.cjs:69:5)
    at new Contract (/Users/kentarovadney/Desktop/code/dusty-faucet/app/node_modules/@polkadot/api-contract/promise/Contract.cjs:16:5)
    at /Users/kentarovadney/Desktop/code/dusty-faucet/app/build/helpers/sendTokens.js:36:22
    at Generator.next (<anonymous>)
    at /Users/kentarovadney/Desktop/code/dusty-faucet/app/build/helpers/sendTokens.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/kentarovadney/Desktop/code/dusty-faucet/app/build/helpers/sendTokens.js:4:12)
    at Object.sendTokens (/Users/kentarovadney/Desktop/code/dusty-faucet/app/build/helpers/sendTokens.js:24:39)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
kentarovadney@Kentaros-MacBook-Air app %

**Comment by VadneyK** [comment]
[updated dependencies and changed some code](https://github.com/PlasmNetwork/dusty-faucet) but still no luck.  the same bug.

![Screen Shot 2021-06-14 at 5 02 18 PM](https://user-images.githubusercontent.com/57117207/121973510-484d0c80-cd32-11eb-97fd-d8d0ba64bc98.png)



Starting bot server...
Plasm Faucet has started
/Users/kentarovadney/Desktop/code/dusty-faucet/app/node_modules/@polkadot/api-contract/node_modules/@polkadot/util/assert.cjs:34
    throw new Error((0, _function.isFunction)(message) ? message() : message);
          ^

Error: You need to connect to a node with a V3 contracts module. Your node does not expose api.tx.contracts.instantiateWithCode on this instance
    at assert (/Users/kentarovadney/Desktop/code/dusty-faucet/app/node_modules/@polkadot/api-contract/node_modules/@polkadot/util/assert.cjs:34:11)
    at new Base (/Users/kentarovadney/Desktop/code/dusty-faucet/app/node_modules/@polkadot/api-contract/base/Base.cjs:26:22)
    at new Contract (/Users/kentarovadney/Desktop/code/dusty-faucet/app/node_modules/@polkadot/api-contract/base/Contract.cjs:67:5)
    at new Contract (/Users/kentarovadney/Desktop/code/dusty-faucet/app/node_modules/@polkadot/api-contract/promise/Contract.cjs:16:5)
    at /Users/kentarovadney/Desktop/code/dusty-faucet/app/build/helpers/sendTokens.js:36:22
    at Generator.next (<anonymous>)
    at /Users/kentarovadney/Desktop/code/dusty-faucet/app/build/helpers/sendTokens.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/kentarovadney/Desktop/code/dusty-faucet/app/build/helpers/sendTokens.js:4:12)
    at Object.sendTokens (/Users/kentarovadney/Desktop/code/dusty-faucet/app/build/helpers/sendTokens.js:24:39)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by VadneyK** [comment]
It seems that dusty network may be pre-version 3:

https://github.com/PlasmNetwork/Plasm/blob/dusty/frame/custom-signatures/Cargo.toml
![Screen Shot 2021-06-14 at 5 17 54 PM](https://user-images.githubusercontent.com/57117207/121974536-76335080-cd34-11eb-9bed-e1c5b21312e4.png)

https://github.com/PlasmNetwork/Plasm/blob/dusty/frame/plasm-rewards/Cargo.toml
![Screen Shot 2021-06-14 at 5 16 51 PM](https://user-images.githubusercontent.com/57117207/121974482-500db080-cd34-11eb-954e-3966d9a064bc.png)

the same seems to apply for all `dusty 4 launches` commit history repos:
https://github.com/PlasmNetwork/Plasm/tree/dusty/frame

so it seems like I may need to refactor the dusty network rust code.

**Comment by VadneyK** [comment]
but the binary plasm 1.9.3 is using v3.0.0... https://github.com/PlasmNetwork/Plasm/blob/dusty/bin/node/runtime/Cargo.toml#L46

**Comment by VadneyK** [comment]
the rpc node uses the most up to date one:
<img width="945" alt="Screen Shot 2021-06-14 at 6 32 57 PM" src="https://user-images.githubusercontent.com/57117207/121979669-7ab13680-cd3f-11eb-822f-4f727cf9c3e3.png">

**Comment by VadneyK** [comment]
Tried a different rpc node and it is still not working so it seems like it is not a client node side error. Is it in the way that I'm using polkadot.js or my smart contract?

![Screen Shot 2021-06-14 at 8 49 36 PM](https://user-images.githubusercontent.com/57117207/121991885-5bbd9f00-cd55-11eb-8af6-21edafcdfeee.png)

**Comment by VadneyK** [comment]
need to wait for api to be ready, similar to discord api https://github.com/polkadot-js/api/issues/3651#issuecomment-861191542
